name: Adjust Debt Daily

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # allows manual trigger

jobs:
  adjust_debt:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger debt adjustment
        uses: supabase/cli-action@v1
        with:
          args: |
            db query "SELECT adjust_debt();" 
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
